on:
  push:
    branches:
      - main

name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        uses: docker/setup-buildx-action@v1
      - name: Login Docker 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: $ {{ secrets.DOCKER_TOKEN }}
      - name: Docker Push
        uses: docker/build-push-actions@v2
        with: 
          push: true
          tags: ${{ secrets.DOCKER_USER }}/test:latest