name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Image
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Check buildx
        run: |
          echo "name: ${{ steps.buildx.outputs.name }}"
          echo "status: ${{ steps.buildx.outputs.status }}"
      - name: Login Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Taggin image
        shell: bash
        id: vars
        run: |
          echo "::set-output name=tag::$(git rev-parse --short HEAD)"
      # - name: Test
      #   run: |
      #     npm i && npm test
      - name: Docker Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/test:latest
            ${{ secrets.DOCKER_USER }}/test:${{ steps.vars.outputs.tag }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: print valor
        if: ${{ github.job.build.status }} == "success"
        run: |
          echo "O step foi um sucesso"
      - run: |
          echo "o step falhou"