name: Build

on:
  push:
    branches:
      - 'main'

env:
  REPO:  ${{ secrets.DOCKER_USER }}/test
  


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Image
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Check buildx
        run: |
          echo "name: ${{ steps.buildx.outputs.name }}"
          echo "status: ${{ steps.buildx.outputs.status }}"
      - name: Login Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Taggin image
        shell: bash
        id: vars
        run: |
          echo "::set-output name=tag::$(git rev-parse --short HEAD)"
          echo "::set-output name=author::$(git log -n 1 | grep Author | cut -d: -d' ' -f2,3)"
          git log -n 1 | grep Author | cut -d: -d' ' -f2,3
      # - name: Test
      #   run: |
      #     npm i && npm test
      - name: Docker Push
        uses: docker/build-push-action@v2
        id: docker
        with:
          push: true
          tags: |
            ${{ env.REPO }}:latest
            ${{ secrets.DOCKER_USER }}/test:${{ steps.vars.outputs.tag }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./pulumi-infra
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jhonsouza/pulumi-infra
          path: infra
          token: ${{ secrets.GIT_TOKEN}}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: cd infra && npm ci
      - uses: pulumi/actions@v3
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          command: destroy
          stack-name: dev
          work-dir: infra
