name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'tag to release'

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git checkout -b release/${{ github.event.inputs.tag_version }} 
          sed -i 's/"version":[[:space:]]"[0-9].[0-9].[0-9]"/"version": "${{ github.event.inputs.tag_version }}"/g' package.json
          cat CHANGELOG.md > changelog
          echo "## [${{ github.event.inputs.tag_version }}]" - $(date '+%Y-%m-%d') > CHANGELOG.md
          cat changelog >> CHANGELOG.md && rm changelog
          git config user.name "Github Actions"
          git config usere.email "tecnologia@passeidireto.com"
          git add package.json CHANGELOG.md
          git commit -m "[AUTOMATED]: update changelog and version"
          git push origin release/${{ github.event.inputs.tag_version }}
      - name: Open Pull Request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "Pulling release/${{ github.event.inputs.tag_version }} into master"
          source_branch: "release/${{ github.event.inputs.tag_version }}"
          destination_branch: "main"
          github_token: ${{ secrets.GIT_TOKEN }}
          pr_body: "*this is a PR created automatically*"