name: generate tag

on:
  push:
    branches: 
      - main
env: 
  - tag-version: $(cat package.json | grep version | cut -d'"' -f4)
jobs:
  creted_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ env.TAG }}"
  merge-back:
    uses: jhonsouza/rest-api-4/.github/workflows/merge-back.yaml@main
      with:
        source_branch: release/${{ env.TAG }}