name: generate tag

on:
  push:
    branches: 
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get version
        id: version
        run: |
          echo "::set-output name=tag_version::$(cat package.json | grep version | cut -d'"' -f4)"
      - name: Generate tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ steps.version.outputs.tag_version }}"
    outputs:
      TAG: ${{ steps.version.outputs.tag_version }}
  merge-back:
    needs: [ create_tag ]
    uses: jhonsouza/rest-api-4/.github/workflows/merge-back.yaml@main
    with:
    source_branch: release/${{ needs.create_tag.outputs.TAG }}
  