name: Merge back in develop

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to merge in develop'
      target_branch:

jobs:
  merge-back:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH 
        run: |
          eval `ssh-agent -s`
          echo ${{ secrets.GIT_KEY }} > gitactions
          chmod 600 gitactions
          ssh-add gitactions
          rm gitactions
      - name: Clone Repo
        run: |
          git clone git@github.com:jhonsouza/rest-api-4.git .
          git fetch git@github.com:jhonsouza/rest-api-4.git
          git checkout -B ${{ github.event.inputs.target_branch }}; git checkout -B ${{ github.event.inputs.target_branch }} refs/remotes/origin/${{ github.event.inputs.target_branch }}
      - name: Configure git
        run: |
          git config push.default simple
          git config user.email "jhonatan.siqueira@passeidireto.com"
          git config user.name "jhonatan siqueira"
          git merge remotes/origin/${{ github.event.inputs.branch }} --no-ff --no-commit
      - name: Check package.json
        run: |
          [ -f package.json ] && git reset HEAD package.json || echo "package.json doesn't exist"
          [ -f package.json ] && git checkout -- package.json || echo "package.json doesn't exist"
      - name: Auto merge
        run: |
          git commit -m "Auto-merge" --allow-empty
          git push git@github.com:jhonsouza/rest-api-4.git ${{ github.event.inputs.target_branch }}:${{ github.event.inputs.target_branch }}
      - name: Remove SSH config
        run: |
          ssh-agent -k